package store

import "backend/models"

var Cities = []models.City{
	{
		Image: "/images/phnopenh.webp", Alt: "Phnom Penh", Rank: 1, Speed: 35, Label: "Popular",
		Country: "Cambodia", City: "Phnom Penh", WeatherEmoji: "☀️", Temp: 33, TempEmoji: "🥵",
		Aqi: 85, AqiEmoji: "😷", Cost: "$1500/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/portugal.webp", Alt: "Lisbon", Rank: 2, Speed: 82, Label: "",
		Country: "Portugal", City: "Lisbon", WeatherEmoji: "🌤️", Temp: 22, TempEmoji: "😊",
		Aqi: 25, AqiEmoji: "😷", Cost: "$2800/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/indonisea.jpg", Alt: "Bali", Rank: 3, Speed: 22, Label: "",
		Country: "Indonesia", City: "Bali", WeatherEmoji: "🌦️", Temp: 29, TempEmoji: "🥵",
		Aqi: 42, AqiEmoji: "😷", Cost: "$1100/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/mexico.webp", Alt: "Mexico City", Rank: 4, Speed: 45, Label: "",
		Country: "Mexico", City: "Mexico City", WeatherEmoji: "🌤️", Temp: 20, TempEmoji: "😊",
		Aqi: 65, AqiEmoji: "😷", Cost: "$1400/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/colombia.jpg", Alt: "Medellín", Rank: 5, Speed: 38, Label: "",
		Country: "Colombia", City: "Medellín", WeatherEmoji: "🌥️", Temp: 24, TempEmoji: "😊",
		Aqi: 35, AqiEmoji: "😷", Cost: "$1300/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/barcelona-spain.webp", Alt: "Barcelona", Rank: 6, Speed: 95, Label: "",
		Country: "Spain", City: "Barcelona", WeatherEmoji: "☀️", Temp: 21, TempEmoji: "😊",
		Aqi: 30, AqiEmoji: "😷", Cost: "$3200/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/georgia.jpg", Alt: "Tbilisi", Rank: 7, Speed: 42, Label: "",
		Country: "Georgia", City: "Tbilisi", WeatherEmoji: "🌥️", Temp: 18, TempEmoji: "😊",
		Aqi: 38, AqiEmoji: "😷", Cost: "$900/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/turkey.webp", Alt: "Istanbul", Rank: 8, Speed: 30, Label: "",
		Country: "Turkey", City: "Istanbul", WeatherEmoji: "🌧️", Temp: 19, TempEmoji: "😊",
		Aqi: 55, AqiEmoji: "😷", Cost: "$1100/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/croatia.webp", Alt: "Split", Rank: 9, Speed: 55, Label: "",
		Country: "Croatia", City: "Split", WeatherEmoji: "☀️", Temp: 23, TempEmoji: "😊",
		Aqi: 20, AqiEmoji: "😷", Cost: "$2200/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/zcechrepublic.jpg", Alt: "Prague", Rank: 10, Speed: 78, Label: "",
		Country: "Czech Republic", City: "Prague", WeatherEmoji: "🌥️", Temp: 15, TempEmoji: "🧥",
		Aqi: 32, AqiEmoji: "😷", Cost: "$2400/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/southkorea.jpg", Alt: "Seoul", Rank: 11, Speed: 120, Label: "",
		Country: "South Korea", City: "Seoul", WeatherEmoji: "🌤️", Temp: 16, TempEmoji: "🧥",
		Aqi: 72, AqiEmoji: "😷", Cost: "$2100/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/romiana.jpg", Alt: "Bucharest", Rank: 12, Speed: 88, Label: "",
		Country: "Romania", City: "Bucharest", WeatherEmoji: "🌥️", Temp: 17, TempEmoji: "😊",
		Aqi: 45, AqiEmoji: "😷", Cost: "$1200/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/japan.jpg", Alt: "Tokyo", Rank: 13, Speed: 95, Label: "",
		Country: "Japan", City: "Tokyo", WeatherEmoji: "🌤️", Temp: 18, TempEmoji: "😊",
		Aqi: 28, AqiEmoji: "😷", Cost: "$3000/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/argentina.webp", Alt: "Buenos Aires", Rank: 14, Speed: 28, Label: "",
		Country: "Argentina", City: "Buenos Aires", WeatherEmoji: "🌤️", Temp: 22, TempEmoji: "😊",
		Aqi: 30, AqiEmoji: "😷", Cost: "$1000/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/vietnam.jpg", Alt: "Ho Chi Minh", Rank: 15, Speed: 24, Label: "",
		Country: "Vietnam", City: "Ho Chi Minh", WeatherEmoji: "🌥️", Temp: 32, TempEmoji: "🥵",
		Aqi: 50, AqiEmoji: "😷", Cost: "$850/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/estonia.webp", Alt: "Tallinn", Rank: 16, Speed: 75, Label: "",
		Country: "Estonia", City: "Tallinn", WeatherEmoji: "🌧️", Temp: 10, TempEmoji: "🧥",
		Aqi: 15, AqiEmoji: "😷", Cost: "$2000/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/morocco.webp", Alt: "Marrakech", Rank: 17, Speed: 18, Label: "",
		Country: "Morocco", City: "Marrakech", WeatherEmoji: "☀️", Temp: 28, TempEmoji: "🥵",
		Aqi: 58, AqiEmoji: "😷", Cost: "$950/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/taiwan.jpg", Alt: "Taipei", Rank: 18, Speed: 85, Label: "",
		Country: "Taiwan", City: "Taipei", WeatherEmoji: "🌦️", Temp: 26, TempEmoji: "😊",
		Aqi: 45, AqiEmoji: "😷", Cost: "$1600/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/hungary.webp", Alt: "Budapest", Rank: 19, Speed: 65, Label: "",
		Country: "Hungary", City: "Budapest", WeatherEmoji: "🌥️", Temp: 16, TempEmoji: "🧥",
		Aqi: 40, AqiEmoji: "😷", Cost: "$1800/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/costa-rica.jpg", Alt: "San José", Rank: 20, Speed: 32, Label: "",
		Country: "Costa Rica", City: "San José", WeatherEmoji: "🌦️", Temp: 24, TempEmoji: "😊",
		Aqi: 22, AqiEmoji: "😷", Cost: "$1700/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/berlin-germany.webp", Alt: "Berlin", Rank: 21, Speed: 72, Label: "",
		Country: "Germany", City: "Berlin", WeatherEmoji: "🌧️", Temp: 14, TempEmoji: "🧥",
		Aqi: 22, AqiEmoji: "😷", Cost: "$2800/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/philipines.webp", Alt: "Manila", Rank: 22, Speed: 20, Label: "",
		Country: "Philippines", City: "Manila", WeatherEmoji: "🌥️", Temp: 25, TempEmoji: "🥵",
		Aqi: 68, AqiEmoji: "😷", Cost: "$1000/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/brazil.jpg", Alt: "Florianópolis", Rank: 23, Speed: 30, Label: "",
		Country: "Brazil", City: "Florianópolis", WeatherEmoji: "☀️", Temp: 26, TempEmoji: "😊",
		Aqi: 18, AqiEmoji: "😷", Cost: "$1400/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/malayisa.jpg", Alt: "Kuala Lumpur", Rank: 24, Speed: 48, Label: "",
		Country: "Malaysia", City: "Kuala Lumpur", WeatherEmoji: "🌦️", Temp: 30, TempEmoji: "🥵",
		Aqi: 55, AqiEmoji: "😷", Cost: "$1200/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/berlin-germany.webp", Alt: "Warsaw", Rank: 25, Speed: 70, Label: "",
		Country: "Poland", City: "Warsaw", WeatherEmoji: "🌥️", Temp: 13, TempEmoji: "🧥",
		Aqi: 48, AqiEmoji: "😷", Cost: "$1600/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/barcelona-spain.webp", Alt: "Athens", Rank: 26, Speed: 40, Label: "",
		Country: "Greece", City: "Athens", WeatherEmoji: "☀️", Temp: 25, TempEmoji: "😊",
		Aqi: 35, AqiEmoji: "😷", Cost: "$2000/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/austin-tx-united-states.webp", Alt: "Montreal", Rank: 28, Speed: 88, Label: "",
		Country: "Canada", City: "Montreal", WeatherEmoji: "🌧️", Temp: 12, TempEmoji: "🧥",
		Aqi: 18, AqiEmoji: "😷", Cost: "$2600/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/malayisa.jpg", Alt: "Colombo", Rank: 29, Speed: 15, Label: "",
		Country: "Sri Lanka", City: "Colombo", WeatherEmoji: "🌦️", Temp: 30, TempEmoji: "🥵",
		Aqi: 48, AqiEmoji: "😷", Cost: "$800/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/barcelona-spain.webp", Alt: "Rome", Rank: 30, Speed: 52, Label: "",
		Country: "Italy", City: "Rome", WeatherEmoji: "☀️", Temp: 22, TempEmoji: "😊",
		Aqi: 32, AqiEmoji: "😷", Cost: "$2900/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/vietnam.jpg", Alt: "Da Nang", Rank: 31, Speed: 28, Label: "",
		Country: "Vietnam", City: "Da Nang", WeatherEmoji: "🌤️", Temp: 27, TempEmoji: "😊",
		Aqi: 35, AqiEmoji: "😷", Cost: "$750/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/malayisa.jpg", Alt: "Chiang Mai", Rank: 32, Speed: 32, Label: "",
		Country: "Malaysia", City: "Kuala Lumpur", WeatherEmoji: "☀️", Temp: 28, TempEmoji: "🥵",
		Aqi: 100, AqiEmoji: "😷", Cost: "$1050/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-85"},
		},
	},
	{
		Image: "/images/croatia.webp", Alt: "Dubrovnik", Rank: 33, Speed: 45, Label: "",
		Country: "Croatia", City: "Dubrovnik", WeatherEmoji: "☀️", Temp: 22, TempEmoji: "😊",
		Aqi: 30, AqiEmoji: "😊", Cost: "$2100/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-80"},
			{Emoji: "💵", Label: "Cost", BarClass: "red w-45"},
			{Emoji: "📡", Label: "Internet", BarClass: "green w-70"},
			{Emoji: "👍", Label: "Liked", BarClass: "green w-85"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-80"},
		},
	},
	{
		Image: "/images/austin-tx-united-states.webp", Alt: "Cape Town", Rank: 34, Speed: 28, Label: "",
		Country: "South Africa", City: "Cape Town", WeatherEmoji: "☀️", Temp: 25, TempEmoji: "😊",
		Aqi: 42, AqiEmoji: "😊", Cost: "$1200/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-75"},
			{Emoji: "💵", Label: "Cost", BarClass: "yellow w-88"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-40"},
			{Emoji: "👍", Label: "Liked", BarClass: "green w-80"},
			{Emoji: "👮", Label: "Safety", BarClass: "red w-50"},
		},
	},
	{
		Image: "/images/berlin-germany.webp", Alt: "Vienna", Rank: 35, Speed: 72, Label: "",
		Country: "Austria", City: "Vienna", WeatherEmoji: "🌤️", Temp: 14, TempEmoji: "😊",
		Aqi: 25, AqiEmoji: "😊", Cost: "$2400/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "yellow w-88"},
			{Emoji: "💵", Label: "Cost", BarClass: "red w-35"},
			{Emoji: "📡", Label: "Internet", BarClass: "green w-90"},
			{Emoji: "👍", Label: "Liked", BarClass: "green w-85"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-95"},
		},
	},
	{
		Image: "/images/phnopenh.webp", Alt: "Siem Reap", Rank: 36, Speed: 22, Label: "",
		Country: "Cambodia", City: "Siem Reap", WeatherEmoji: "☀️", Temp: 35, TempEmoji: "🥵",
		Aqi: 78, AqiEmoji: "😷", Cost: "$850/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-75"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-95"},
			{Emoji: "📡", Label: "Internet", BarClass: "red w-30"},
			{Emoji: "👍", Label: "Liked", BarClass: "green w-80"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-70"},
		},
	},
	{
		Image: "/images/asuncion-paraguay.webp", Alt: "Lima", Rank: 37, Speed: 38, Label: "",
		Country: "Peru", City: "Lima", WeatherEmoji: "🌤️", Temp: 21, TempEmoji: "😊",
		Aqi: 65, AqiEmoji: "😷", Cost: "$1100/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-72"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-85"},
			{Emoji: "📡", Label: "Internet", BarClass: "green w-60"},
			{Emoji: "👍", Label: "Liked", BarClass: "green w-75"},
			{Emoji: "👮", Label: "Safety", BarClass: "red w-55"},
		},
	},
	{
		Image: "/images/malayisa.jpg", Alt: "Singapore", Rank: 38, Speed: 95, Label: "",
		Country: "Singapore", City: "Singapore", WeatherEmoji: "☀️", Temp: 31, TempEmoji: "🥵",
		Aqi: 55, AqiEmoji: "😊", Cost: "$3200/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-90"},
			{Emoji: "💵", Label: "Cost", BarClass: "red w-20"},
			{Emoji: "📡", Label: "Internet", BarClass: "green w-95"},
			{Emoji: "👍", Label: "Liked", BarClass: "yellow w-88"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-95"},
		},
	},
	{
		Image: "/images/berlin-germany.webp", Alt: "Amsterdam", Rank: 39, Speed: 68, Label: "",
		Country: "Netherlands", City: "Amsterdam", WeatherEmoji: "🌧️", Temp: 11, TempEmoji: "🥶",
		Aqi: 20, AqiEmoji: "😊", Cost: "$2800/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-85"},
			{Emoji: "💵", Label: "Cost", BarClass: "red w-25"},
			{Emoji: "📡", Label: "Internet", BarClass: "yellow w-88"},
			{Emoji: "👍", Label: "Liked", BarClass: "green w-82"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-80"},
		},
	},
	{
		Image: "/images/colombia.jpg", Alt: "Bogotá", Rank: 40, Speed: 30, Label: "",
		Country: "Colombia", City: "Bogotá", WeatherEmoji: "🌤️", Temp: 18, TempEmoji: "😊",
		Aqi: 58, AqiEmoji: "😊", Cost: "$1000/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-72"},
			{Emoji: "💵", Label: "Cost", BarClass: "green w-90"},
			{Emoji: "📡", Label: "Internet", BarClass: "green w-55"},
			{Emoji: "👍", Label: "Liked", BarClass: "green w-78"},
			{Emoji: "👮", Label: "Safety", BarClass: "red w-45"},
		},
	},
	{
		Image: "/images/austin-tx-united-states.webp", Alt: "Dubai", Rank: 41, Speed: 85, Label: "",
		Country: "UAE", City: "Dubai", WeatherEmoji: "☀️", Temp: 38, TempEmoji: "🥵",
		Aqi: 110, AqiEmoji: "😷", Cost: "$2900/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "green w-78"},
			{Emoji: "💵", Label: "Cost", BarClass: "red w-20"},
			{Emoji: "📡", Label: "Internet", BarClass: "green w-90"},
			{Emoji: "👍", Label: "Liked", BarClass: "green w-70"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-92"},
		},
	},
	{
		Image: "/images/japan.jpg", Alt: "Osaka", Rank: 42, Speed: 78, Label: "",
		Country: "Japan", City: "Osaka", WeatherEmoji: "🌤️", Temp: 16, TempEmoji: "😊",
		Aqi: 35, AqiEmoji: "😊", Cost: "$1800/mo",
		Ratings: []models.Rating{
			{Emoji: "⭐️", Label: "Overall", BarClass: "yellow w-88"},
			{Emoji: "💵", Label: "Cost", BarClass: "red w-40"},
			{Emoji: "📡", Label: "Internet", BarClass: "green w-85"},
			{Emoji: "👍", Label: "Liked", BarClass: "green w-90"},
			{Emoji: "👮", Label: "Safety", BarClass: "green w-95"},
		},
	},
}
